### ISSUE TITLE
argparse.ArgumentError: argument --allow-overriding

### ISSUE THREAD

**Issue by tonynajjar** [colcon/colcon-override-check#3]
Hello, I'm getting this on Ubuntu 18/Galactic but not on Ubuntu 20/Galactic. Any idea?

```
root@amr47:/code# colcon build --symlink-install --packages-select rosbag2_storage_mcap
ERROR:colcon.colcon_core.package_selection:Exception in package selection extension 'override_check': argument --allow-overriding: conflicting option string: --allow-overriding
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_selection/__init__.py", line 109, in _add_package_selection_arguments
    retval = extension.add_arguments(parser=group)
  File "/usr/lib/python3/dist-packages/colcon_override_check/package_selection/override_check.py", line 58, in add_arguments
    help='Allow building packages that exist in underlay workspaces')
  File "/usr/local/lib/python3.6/dist-packages/colcon_mixin/mixin/mixin_argument.py", line 100, in add_argument
    return super().add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/argument_parser/destination_collector.py", line 46, in add_argument
    argument = super().add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/argument_parser/type_collector.py", line 34, in add_argument
    ret = super().add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/argument_parser/__init__.py", line 171, in add_argument
    return self._parser.add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_defaults/argument_parser/defaults.py", line 78, in add_argument
    argument = super().add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/argument_parser/destination_collector.py", line 46, in add_argument
    argument = super().add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/argument_parser/type_collector.py", line 34, in add_argument
    ret = super().add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/argument_parser/__init__.py", line 171, in add_argument
    return self._parser.add_argument(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_argcomplete/argument_parser/argcomplete/__init__.py", line 49, in add_argument
    argument = self._parser.add_argument(*args, **kwargs)
  File "/usr/lib/python3.6/argparse.py", line 1361, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1565, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.6/argparse.py", line 1375, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.6/argparse.py", line 1514, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.6/argparse.py", line 1523, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --allow-overriding: conflicting option string: --allow-overriding
```

**Comment by cottsay** [comment]
You're using an older version of colcon_core. Please try updating to the latest version.
